-- GENERATED by db/holidays_seed.mjs — do not hand-edit; re-run the script instead.
-- Israeli public holidays + company closures, civil years 2026–2027 (5786/5787).
-- Source: Hebcal Israel calendar (maj=on, i=on). חול המועד סוכות = company closure (עמיחי, 18.9).
-- Apply AFTER db/company_holidays.sql.
insert into public.company_holidays (date, name, kind, required, created_by) values
  ('2026-04-02', 'פסח א׳', 'holiday', false, 'hebcal'),
  ('2026-04-03', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2026-04-04', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2026-04-05', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2026-04-06', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2026-04-07', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2026-04-08', 'פסח ז׳', 'holiday', false, 'hebcal'),
  ('2026-05-22', 'שבועות', 'holiday', false, 'hebcal'),
  ('2026-09-12', 'ראש השנה 5787', 'holiday', false, 'hebcal'),
  ('2026-09-13', 'ראש השנה ב׳', 'holiday', false, 'hebcal'),
  ('2026-09-21', 'יום כיפור', 'holiday', false, 'hebcal'),
  ('2026-09-26', 'סוכות א׳', 'holiday', false, 'hebcal'),
  ('2026-09-27', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-09-28', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-09-29', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-09-30', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-10-01', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-10-02', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2026-10-03', 'שמיני עצרת', 'holiday', false, 'hebcal'),
  ('2027-04-22', 'פסח א׳', 'holiday', false, 'hebcal'),
  ('2027-04-23', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2027-04-24', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2027-04-25', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2027-04-26', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2027-04-27', 'חול המועד פסח', 'chol_hamoed', true, 'hebcal'),
  ('2027-04-28', 'פסח ז׳', 'holiday', false, 'hebcal'),
  ('2027-06-11', 'שבועות', 'holiday', false, 'hebcal'),
  ('2027-10-02', 'ראש השנה 5788', 'holiday', false, 'hebcal'),
  ('2027-10-03', 'ראש השנה ב׳', 'holiday', false, 'hebcal'),
  ('2027-10-11', 'יום כיפור', 'holiday', false, 'hebcal'),
  ('2027-10-16', 'סוכות א׳', 'holiday', false, 'hebcal'),
  ('2027-10-17', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-18', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-19', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-20', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-21', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-22', 'חול המועד סוכות', 'company_closure', false, 'hebcal'),
  ('2027-10-23', 'שמיני עצרת', 'holiday', false, 'hebcal')
on conflict (date) do update
  set name = excluded.name, kind = excluded.kind
  -- a date עידן/עמיחי already toggled by hand keeps its own `required`
  where public.company_holidays.created_by = 'hebcal';

-- Verify:
--   select date, name, kind, required from public.company_holidays
--    where date between '2026-09-01' and '2026-10-31' order by date;
