// Turns db/meter_burns_seed.csv (exported from the EMS prod DB) into db/meter_burns_seed.sql.
// Re-runnable: the INSERT upserts ONLY the EMS-sourced columns, never status/burned_*/generator_id/note.
// Run: node db/gen_meter_burns_seed.mjs
import fs from 'node:fs';
const csvPath = new URL('./meter_burns_seed.csv', import.meta.url);
const outPath = new URL('./meter_burns_seed.sql', import.meta.url);

// minimal RFC-4180 parser (fields may be quoted and contain commas/quotes; no embedded newlines in our export)
export function parseCsv(text) {
  const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter(l => l.length);
  const split = (line) => {
    const out = []; let cur = '', q = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (q) { if (ch === '"') { if (line[i + 1] === '"') { cur += '"'; i++; } else q = false; } else cur += ch; }
      else if (ch === '"') q = true;
      else if (ch === ',') { out.push(cur); cur = ''; }
      else cur += ch;
    }
    out.push(cur); return out;
  };
  const head = split(lines[0]);
  return lines.slice(1).map(l => { const v = split(l); const o = {}; head.forEach((h, i) => o[h] = v[i] ?? ''); return o; });
}
const q = (s) => s === '' ? 'null' : "'" + String(s).replace(/'/g, "''") + "'";
const n = (s) => s === '' ? 'null' : String(Number(s));
export function rowToValues(r) {
  return `(${q(r.meter_id)}::uuid, ${q(r.serial)}, ${q(r.site)}, ${r.site_id ? q(r.site_id) + '::uuid' : 'null'}, ${q(r.meter_type)}, ${q(r.address)}, ${n(r.role_code)}, ${n(r.ct_ratio)}, ${q(r.parent_serial)}, ${q(r.solar_names)})`;
}
export function buildSql(rows) {
  return `-- GENERATED by db/gen_meter_burns_seed.mjs from db/meter_burns_seed.csv — ${rows.length} rows. Do not edit by hand.
insert into public.meter_burns (meter_id, serial, site, site_id, meter_type, address, role_code, ct_ratio, parent_serial, solar_names) values
${rows.map(rowToValues).join(',\n')}
on conflict (meter_id) do update set
  serial = excluded.serial, site = excluded.site, site_id = excluded.site_id, meter_type = excluded.meter_type,
  address = excluded.address, role_code = excluded.role_code, ct_ratio = excluded.ct_ratio,
  parent_serial = excluded.parent_serial, solar_names = excluded.solar_names;
`;
}
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  const rows = parseCsv(fs.readFileSync(csvPath, 'utf8'));
  fs.writeFileSync(outPath, buildSql(rows));
  console.log(`wrote db/meter_burns_seed.sql with ${rows.length} rows`);
}
