// One-shot seed generator for `company_holidays` (spec §7e, Task 12).
//
//   node db/holidays_seed.mjs            → writes db/company_holidays_seed.sql
//   node db/holidays_seed.mjs --print    → prints the rows it would write, writes nothing
//
// WHY A SCRIPT AND NOT A HAND-TYPED LIST: the Hebrew calendar moves every year, and the one
// thing this table must never be is quietly stale. The script is re-runnable — point it at
// the next two civil years and paste the file.
//
// SOURCE: Hebcal's Israel calendar (`i=on`), major holidays only (`maj=on`), exactly the
// query the spec names. Each item carries `hebrew` (the name we store) and `yomtov`.
//
// CLASSIFICATION (עמיחי's ruling, 18.9):
//   • yom tov (ראש השנה / יום כיפור / סוכות א׳ / שמיני עצרת / פסח / שבועות) → kind 'holiday'
//   • חול המועד סוכות                                                      → kind 'company_closure'
//   • חול המועד פסח                                                        → kind 'chol_hamoed', required=true
//     (the company has not closed for it; עמיחי decides, and until he does the day is a
//      normal work day — `required=true` is the safe side: it stays in the missing list.)
// Everything written here has `required=false` unless the line above says otherwise.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, 'company_holidays_seed.sql');
const YEARS = [2026, 2027];

const url = (year) =>
  `https://www.hebcal.com/hebcal?v=1&cfg=json&maj=on&min=off&mod=off&nx=off&year=${year}` +
  `&month=x&ss=off&mf=off&c=off&geo=none&i=on`;

/** A Hebcal item → our row, or null when the date is not a day off at all. */
export function classify(item) {
  const date = String(item.date || '').slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null;
  const title = String(item.title || '');
  const hebrew = String(item.hebrew || title);
  const chm = /CH['’]{0,2}"?M|CH''M|Chol ha-Mo'?ed/i.test(title);
  if (chm) {
    const sukkot = /sukkot/i.test(title);
    return sukkot
      ? { date, name: 'חול המועד סוכות', kind: 'company_closure', required: false }
      : { date, name: 'חול המועד פסח', kind: 'chol_hamoed', required: true };
  }
  if (item.yomtov === true) return { date, name: hebrew, kind: 'holiday', required: false };
  return null;
}

const dayAfter = (d) => { const x = new Date(d + 'T00:00:00Z'); x.setUTCDate(x.getUTCDate() + 1); return x.toISOString().slice(0, 10); };

/**
 * Close the gap inside an intermediate-days run. Hebcal lists הושענא רבה (the last day of
 * חול המועד סוכות) under its own name, not as CH"M, so a straight mapping leaves 2.10.26
 * out — and the ruling is that the whole 27.9–2.10 stretch is a company closure. Anything
 * that falls BETWEEN an intermediate day and the yom tov that ends the festival inherits the
 * intermediate day's classification. Nothing outside such a run is touched.
 */
export function fillClosureGaps(rows) {
  const sorted = [...rows].sort((a, b) => a.date.localeCompare(b.date));
  const out = [];
  for (let i = 0; i < sorted.length; i++) {
    const cur = sorted[i], next = sorted[i + 1];
    out.push(cur);
    if (!next) continue;
    const intermediate = cur.kind === 'company_closure' || cur.kind === 'chol_hamoed';
    if (!intermediate || next.kind !== 'holiday') continue;
    for (let d = dayAfter(cur.date); d < next.date; d = dayAfter(d)) {
      out.push({ date: d, name: cur.name, kind: cur.kind, required: cur.required });
    }
  }
  return out;
}

function sqlStr(s) { return "'" + String(s).replace(/'/g, "''") + "'"; }

export function toSql(rows) {
  const body = rows
    .map(r => `  (${sqlStr(r.date)}, ${sqlStr(r.name)}, ${sqlStr(r.kind)}, ${r.required ? 'true' : 'false'}, 'hebcal')`)
    .join(',\n');
  return `-- GENERATED by db/holidays_seed.mjs — do not hand-edit; re-run the script instead.
-- Israeli public holidays + company closures, civil years ${YEARS.join('–')} (5786/5787).
-- Source: Hebcal Israel calendar (maj=on, i=on). חול המועד סוכות = company closure (עמיחי, 18.9).
-- Apply AFTER db/company_holidays.sql.
insert into public.company_holidays (date, name, kind, required, created_by) values
${body}
on conflict (date) do update
  set name = excluded.name, kind = excluded.kind
  -- a date עידן/עמיחי already toggled by hand keeps its own \`required\`
  where public.company_holidays.created_by = 'hebcal';

-- Verify:
--   select date, name, kind, required from public.company_holidays
--    where date between '2026-09-01' and '2026-10-31' order by date;
`;
}

/**
 * The 2026–2027 list as Hebcal publishes it, used when the network is not reachable from the
 * machine running this script (an agent sandbox, CI). Kept in the file on purpose: the seed
 * must be reproducible offline, and the numbers are public-calendar facts, not a guess.
 */
export const FALLBACK = [
  // civil 2026
  { date: '2026-04-02', name: 'פסח א׳', kind: 'holiday', required: false },
  { date: '2026-04-03', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2026-04-04', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2026-04-05', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2026-04-06', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2026-04-07', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2026-04-08', name: 'פסח ז׳', kind: 'holiday', required: false },
  { date: '2026-05-22', name: 'שבועות', kind: 'holiday', required: false },
  { date: '2026-09-12', name: 'ראש השנה 5787', kind: 'holiday', required: false },
  { date: '2026-09-13', name: 'ראש השנה ב׳', kind: 'holiday', required: false },
  { date: '2026-09-21', name: 'יום כיפור', kind: 'holiday', required: false },
  { date: '2026-09-26', name: 'סוכות א׳', kind: 'holiday', required: false },
  { date: '2026-09-27', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-09-28', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-09-29', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-09-30', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-10-01', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-10-02', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2026-10-03', name: 'שמיני עצרת', kind: 'holiday', required: false },
  // civil 2027
  { date: '2027-04-22', name: 'פסח א׳', kind: 'holiday', required: false },
  { date: '2027-04-23', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2027-04-24', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2027-04-25', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2027-04-26', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2027-04-27', name: 'חול המועד פסח', kind: 'chol_hamoed', required: true },
  { date: '2027-04-28', name: 'פסח ז׳', kind: 'holiday', required: false },
  { date: '2027-06-11', name: 'שבועות', kind: 'holiday', required: false },
  { date: '2027-10-02', name: 'ראש השנה 5788', kind: 'holiday', required: false },
  { date: '2027-10-03', name: 'ראש השנה ב׳', kind: 'holiday', required: false },
  { date: '2027-10-11', name: 'יום כיפור', kind: 'holiday', required: false },
  { date: '2027-10-16', name: 'סוכות א׳', kind: 'holiday', required: false },
  { date: '2027-10-17', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-18', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-19', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-20', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-21', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-22', name: 'חול המועד סוכות', kind: 'company_closure', required: false },
  { date: '2027-10-23', name: 'שמיני עצרת', kind: 'holiday', required: false },
];

async function fetchYear(year) {
  const r = await fetch(url(year), { headers: { accept: 'application/json' } });
  if (!r.ok) throw new Error('hebcal ' + year + ' → HTTP ' + r.status);
  const j = await r.json();
  return (j.items || []).map(classify).filter(Boolean);
}

async function main() {
  let rows = [];
  let source = 'hebcal (live)';
  try {
    for (const y of YEARS) rows = rows.concat(await fetchYear(y));
    if (!rows.length) throw new Error('hebcal returned no major holidays');
  } catch (e) {
    console.warn('⚠️  Hebcal fetch failed (' + e.message + ') — using the built-in 2026–2027 list.');
    rows = FALLBACK.slice();
    source = 'built-in fallback list (network unavailable)';
  }
  // one row per date, ascending
  const byDate = new Map();
  for (const r of fillClosureGaps(rows)) byDate.set(r.date, r);
  const out = [...byDate.values()].sort((a, b) => a.date.localeCompare(b.date));
  if (process.argv.includes('--print')) { console.table(out); return; }
  writeFileSync(OUT, toSql(out), 'utf8');
  console.log(`✅ ${out.length} rows → ${OUT}  (source: ${source})`);
}

// Windows-safe "am I the entry point?" — `file://` + a backslash path never matches
// import.meta.url, which is why this uses pathToFileURL.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
