-- ══════════════════════════════════════════════════════════════════════════════
-- `kibbutzim` — the kibbutz card list as DATA (spec §7b, "סיגמה 2.00").
-- Until now every card was hard-coded in index.html; adding one needed a commit.
-- `name` is the canonical join key used everywhere else (visits.kibbutz,
-- kibbutz_meeting_notes, KIBBUTZ_SITE_MAP) — it equals the old card data-name.
-- Delete is never used: archiving (archived_at) keeps that history reachable.
-- `kind`/`parent` describe a sub-site hanging off a kibbutz (no UI yet — a later
-- task fills them in; the card render already places a sub-site under its parent).
-- RLS follows the same staged pattern as db/rls_staged.sql (anon reads, the
-- bridge-minted `authenticated` role writes); the viewer role is blocked
-- client-side, like everywhere else in the app.
-- ══════════════════════════════════════════════════════════════════════════════
create table if not exists kibbutzim (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,          -- canonical = old card data-name
  display_name text,
  section text not null check (section in ('new','active')),
  energy text[] not null default '{electric}',
  marketing boolean not null default false,
  region text not null default '',
  kind text not null default 'kibbutz' check (kind in ('kibbutz','subsite')),
  parent text,                        -- kibbutzim.name of the parent, when kind='subsite'
  ems_site_ids text[] not null default '{}',
  archived_at timestamptz,
  created_by text, created_at timestamptz default now(), updated_at timestamptz default now()
);
-- idempotent for an already-created table (the columns were added after the first cut)
alter table kibbutzim add column if not exists kind text not null default 'kibbutz';
alter table kibbutzim add column if not exists parent text;
alter table kibbutzim enable row level security;
drop policy if exists kibbutzim_read on kibbutzim;
create policy kibbutzim_read on kibbutzim for select using (true);
drop policy if exists kibbutzim_write on kibbutzim;
create policy kibbutzim_write on kibbutzim for all to authenticated using (true) with check (true);

-- generated by db/kibbutzim_seed.mjs — 54 kibbutzim
insert into kibbutzim (name, display_name, section, energy, marketing, region) values
  ('גבת', null, 'new', '{"electric"}', false, 'העמקים'),
  ('יגור', null, 'new', '{"electric"}', false, 'העמקים'),
  ('חוקוק', null, 'new', '{"electric"}', false, 'העמקים'),
  ('דגניה', 'דגניה א', 'new', '{"electric"}', false, 'העמקים'),
  ('עין חרוד מאוחד', null, 'active', '{"electric"}', true, 'העמקים'),
  ('אלומות', null, 'new', '{"electric"}', false, 'העמקים'),
  ('בית זרע', null, 'active', '{"electric"}', true, 'העמקים'),
  ('כנרת', null, 'active', '{"electric"}', true, 'העמקים'),
  ('כפר עזה', null, 'active', '{"electric"}', true, 'דרום, עוטף עזה והנגב'),
  ('יסעור', null, 'active', '{"electric"}', true, 'גליל וגולן'),
  ('מגידו', null, 'active', '{"electric"}', true, 'העמקים'),
  ('ניר עציון', null, 'active', '{"electric"}', true, 'מישור החוף והשרון'),
  ('כפר מנחם', null, 'active', '{"electric"}', true, 'שפלה ומרכז'),
  ('משואות יצחק', null, 'active', '{"electric"}', true, 'דרום, עוטף עזה והנגב'),
  ('עין דור', null, 'new', '{"electric"}', false, 'העמקים'),
  ('דגניה ב', 'דגניה ב''', 'new', '{"electric"}', false, ''),
  ('דפנה', null, 'new', '{"electric"}', false, ''),
  ('משמר השרון', null, 'active', '{"electric"}', false, 'מישור החוף והשרון'),
  ('תל קציר', null, 'active', '{"electric"}', false, 'העמקים'),
  ('כפר גלעדי', null, 'active', '{"electric"}', false, 'גליל וגולן'),
  ('גניגר', null, 'active', '{"electric"}', false, 'העמקים'),
  ('גבים', null, 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('מעוז חיים', null, 'active', '{"electric"}', false, 'העמקים'),
  ('אפיקים', null, 'active', '{"electric"}', false, 'העמקים'),
  ('גברעם', null, 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('עין המפרץ', null, 'active', '{"electric","water"}', false, 'גליל וגולן'),
  ('אלונים', null, 'active', '{"electric"}', false, 'העמקים'),
  ('אור הנר חשמל', 'אור הנר — חשמל', 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('אור הנר גז', 'אור הנר — גז', 'active', '{"gas"}', false, 'דרום, עוטף עזה והנגב'),
  ('מתחם חינוך שער הנגב', null, 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('שדה אליהו', null, 'active', '{"electric"}', false, 'העמקים'),
  ('קיבוץ גת', null, 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('מעלה גלבוע', null, 'active', '{"electric"}', false, 'העמקים'),
  ('חולדה', null, 'active', '{"electric"}', false, 'שפלה ומרכז'),
  ('שריד', null, 'active', '{"electric"}', false, 'העמקים'),
  ('גבעת חיים מאוחד', null, 'active', '{"electric"}', false, 'מישור החוף והשרון'),
  ('עין השופט', null, 'active', '{"electric","water"}', false, 'העמקים'),
  ('קבוצת יבנה', null, 'active', '{"electric"}', false, 'שפלה ומרכז'),
  ('להב', null, 'active', '{"electric"}', false, 'דרום, עוטף עזה והנגב'),
  ('עין חרוד איחוד', null, 'active', '{"electric"}', true, 'העמקים'),
  ('אפיק', null, 'active', '{"electric"}', true, 'גליל וגולן'),
  ('חוצות יגור', null, 'active', '{"electric"}', true, 'העמקים'),
  ('שלוחות', null, 'active', '{"electric"}', true, 'העמקים'),
  ('אגודת המים עמק הירדן', null, 'active', '{"electric"}', true, 'העמקים'),
  ('כפר מסריק', null, 'active', '{"electric"}', true, 'גליל וגולן'),
  ('שער הגולן', null, 'active', '{"electric"}', true, 'העמקים'),
  ('בית אריזה גלבוע', null, 'active', '{"electric"}', true, 'העמקים'),
  ('דביר', null, 'active', '{"electric"}', true, 'דרום, עוטף עזה והנגב'),
  ('לביא', null, 'active', '{"electric"}', true, 'גליל וגולן'),
  ('מגן', null, 'active', '{"electric"}', true, 'דרום, עוטף עזה והנגב'),
  ('פרחי אביב', null, 'active', '{"electric"}', true, 'מישור החוף והשרון'),
  ('קיבוץ ניצנים', null, 'active', '{"electric"}', true, 'דרום, עוטף עזה והנגב'),
  ('כפר דניאל', null, 'active', '{"electric"}', true, 'שפלה ומרכז'),
  ('רמות מנשה', null, 'active', '{"electric"}', true, 'העמקים')
on conflict (name) do nothing;
