// The GENERATED CSS, in one place: `css/app.min.css` and the critical block inlined into
// index.html. `build.mjs` writes them, `build.mjs --check` and `test-css-build.mjs` verify that
// what is committed is what the sources produce.
//
// WHY a freshness contract at all: `css/app.css` and `css/critical.css` are hand-written sources
// whose OUTPUT is what the browser loads. Editing a source and committing without running
// `node build.mjs` ships the old bytes — the change simply has no effect, and nothing complains.
// Each output therefore carries the sha256 of its source, so staleness is a checkable fact and
// not a code review's job.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = rel => readFileSync(resolve(ROOT, rel), 'utf8');

/** First 16 hex chars of the source's sha256 — enough to pin a file, short enough to read. */
export function srcHash(text) {
  // The sources are committed with CRLF on Windows and LF elsewhere; hash the CONTENT, not the
  // line endings, or the check fails on a fresh clone for no reason.
  return createHash('sha256').update(String(text).replace(/\r\n/g, '\n'), 'utf8').digest('hex').slice(0, 16);
}

export const APP_MIN_PATH = 'css/app.min.css';
export const CRITICAL_MARKER = /(<!-- critical:start[^>]*-->)([\s\S]*?)(<!-- critical:end -->)/;

/** The exact bytes `css/app.min.css` must contain for the current `css/app.css`. */
export function buildAppMin(source = read('css/app.css')) {
  const min = esbuild.transformSync(source, { loader: 'css', minify: true }).code;
  return '/* GENERATED by build.mjs from css/app.css — do not edit. src-sha256:'
    + srcHash(source) + ' */\n' + min + '\n';
}

/** The `<style>` block (and its start marker) that index.html must carry for css/critical.css. */
export function buildCritical(source = read('css/critical.css')) {
  const min = esbuild.transformSync(source, { loader: 'css', minify: true }).code.trim();
  const hash = srcHash(source);
  return {
    hash,
    marker: '<!-- critical:start — generated from css/critical.css by build.mjs; do NOT hand-edit.'
      + ' src-sha256:' + hash + ' -->',
    style: '<style>' + min + '</style>',
  };
}

/** Replace the marked block in an index.html string with the freshly generated one. */
export function inlineCritical(html, built = buildCritical()) {
  if (!CRITICAL_MARKER.test(html)) {
    throw new Error('index.html has no <!-- critical:start --> … <!-- critical:end --> block');
  }
  return html.replace(CRITICAL_MARKER, (m, start, body, end) =>
    built.marker + '\n' + built.style + '\n' + end);
}

/**
 * Is what is committed what the sources produce? Pure: reads, never writes.
 * @returns {{ok: boolean, problems: string[]}}
 */
export function checkGeneratedCss() {
  const problems = [];

  // ── css/app.min.css ──────────────────────────────────────────────────────
  try {
    const want = buildAppMin();
    const have = read(APP_MIN_PATH);
    const wantHash = /src-sha256:([0-9a-f]{16})/.exec(want)?.[1];
    const haveHash = /src-sha256:([0-9a-f]{16})/.exec(have)?.[1];
    if (!haveHash) problems.push(`${APP_MIN_PATH} carries no src-sha256 stamp — run \`node build.mjs\``);
    else if (haveHash !== wantHash) {
      problems.push(`${APP_MIN_PATH} was built from a different css/app.css (stamp ${haveHash}, source is ${wantHash}) — run \`node build.mjs\``);
    }
    if (have.replace(/\r\n/g, '\n') !== want.replace(/\r\n/g, '\n')) {
      problems.push(`${APP_MIN_PATH} does not match what css/app.css minifies to — run \`node build.mjs\` (never hand-edit it)`);
    }
  } catch (e) {
    problems.push(`${APP_MIN_PATH}: ${e.message}`);
  }

  // ── the inlined critical block in index.html ─────────────────────────────
  try {
    const html = read('index.html');
    const m = CRITICAL_MARKER.exec(html);
    if (!m) problems.push('index.html has no critical:start … critical:end block — run `node build.mjs`');
    else {
      const built = buildCritical();
      const haveHash = /src-sha256:([0-9a-f]{16})/.exec(m[1])?.[1];
      if (!haveHash) problems.push('index.html\'s critical marker carries no src-sha256 stamp — run `node build.mjs`');
      else if (haveHash !== built.hash) {
        problems.push(`index.html's inlined critical CSS was built from a different css/critical.css (stamp ${haveHash}, source is ${built.hash}) — run \`node build.mjs\``);
      }
      if (m[2].trim() !== built.style) {
        problems.push('index.html\'s inlined critical CSS does not match what css/critical.css minifies to — run `node build.mjs` (never hand-edit the block)');
      }
    }
  } catch (e) {
    problems.push(`index.html: ${e.message}`);
  }

  return { ok: problems.length === 0, problems };
}
